### ISSUE TITLE
Readme example incomplete

### ISSUE THREAD

**Issue by mchampine** [mikera/clisk#4]
The first example in the readme (render-lit) doesn't work because vblocks is undefined.  I found it on your blog:

https://clojurefun.wordpress.com/2012/08/12/voronoi-rocks/

(def vblocks 
  (v\* 5.0 
      (voronoi-function 
        `(Math/sqrt (- (\* ~'y ~'y) (\* ~'x ~'x))))))

Enjoying clisk btw, thanks for making it!

**Comment by mikera** [comment]
Good spot, thanks! 

Fixed by updating the README (vblocks is nice but didn't seem general enough to be defined in Clisk itself)
