### ISSUE TITLE
Is is possible use your library for rendering image sequense in single window?

### ISSUE THREAD

**Issue by proofit404** [mikera/clisk#5]
For example I need render png image sequence in single window in my app. Is it possible to use you library for my aim?

P.S. Sorry for this issue, but I can't find other way to contact with you.

**Comment by mikera** [comment]
Yes that should definitely be possible. 

`(clisk.core/img some-function)` basically creates a BufferedImage, which you can render into a window however you like. With a bit more hacking you could create a sequence of BufferedImages and play them in an animation (in a loop, for example).

**Comment by proofit404** [comment]
Yes, works fine. Thank you for feed back.
