### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by nodename** [mikera/clisk#6]
Hello Mike
I am studying the library and through rough pattern-matching on existing code without much understanding I have come up with

```
(defn x-gradient
  ([a b]
    (clisk.functions/lerp (vfrac x) a b)))
```

which I have stuck into my copy of clisk.patterns.clj.

Could you please comment on whether this is at all correct (image looks a bit off) and what would be the right thing to do?

Thanks!

**Comment by mikera** [comment]
Hi, you need to use the vectorised version of lerp, called vlerp:

```
(defn x-gradient
   ([a b]
     (clisk.functions/vlerp  a b x)))

(show (x-gradient 0 1))
```

lerp itself is just a utility function that works on scalars

**Comment by nodename** [comment]
Thanks!
... I don't find vlerp in the source on github...

**Comment by mikera** [comment]
should be just below lerp in functions.clj

I need to document some of this stuff better :-)

**Comment by mikera** [comment]
Sorry I was looking at the wrong clisk version in git! Latest version should use lerp
