### ISSUE TITLE
vlerp not in github source

### ISSUE THREAD

**Issue by nodename** [mikera/clisk#7]
:)!

**Comment by mikera** [comment]
Hi there, just realised I was looking at the wrong source branch. What was called vlerp is now called lerp. I think that is a better name. So your gradient function using lerp should work fine....

**Comment by nodename** [comment]
Ah thanks. If I have further questions is this the best place to ask?

**Comment by mikera** [comment]
Sure fine to ask questions here.... there isn't anywhere else at the moment!
