### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by odyssomay** [mikera/clisk#9]
I could not find any information on what license is used. That
effectively means that clisk is under copright protection, which means
it's not possible to - without risk - use it for either open source
or commercial projects.

Of course you could let it stay under copyright, but I don't think 
that's what you want. :)

**Comment by mikera** [comment]
Good spot - It's LGPL, I've added details to the latest develop branch.

**Comment by odyssomay** [comment]
Nice! :+1:
